<div style="background-image: url(//invipay.com/promo/images/logo_slogan_small.png) !important; background-repeat: no-repeat !important; background-size: auto 30px !important; background-position: 10px center !important; padding-left: 130px !important;">
	<span><?php echo $this->getLabelTitle(); ?></span>
	<br>
	<a href="#" class="learn_more" onclick="window.open('//invipay.com/zakupy-w-internecie-z-invipay-com/', 'inviPayLearnMore', 'width=400,height=700,status=0,titlebar=0,toolbar=0,menubar=0,scrollbars=1'); return false;" style="margin: 0px !important; float: none !important; color: #00B2DD !important; font-weight: normal !important;">Kliknij tutaj, aby dowiedzieć się, jak to działa</a>
</div>